const mongoose = require('mongoose');

const AttendanceSchema = new mongoose.Schema({
  teacher: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Teacher',
    required: true
  },
  // For backwards compatibility
  teacherId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Teacher'
  },
  date: {
    type: Date,
    required: true,
    default: Date.now
  },
  // Using both naming conventions for compatibility
  timeIn: {
    type: String,
    default: null
  },
  timeOut: {
    type: String,
    default: null
  },
  checkIn: {
    type: String,
    default: null
  },
  checkOut: {
    type: String,
    default: null
  },
  status: {
    type: String,
    enum: ['present', 'absent', 'late', 'half-day', 'leave', 'holiday'],
    default: 'present'
  },
  workHours: {
    type: Number,
    default: 0
  },
  salaryDeduction: {
    type: Number,
    default: 0
  },
  comment: {
    type: String,
    trim: true
  },
  autoGenerated: {
    type: Boolean,
    default: false
  },
  createdAt: {
    type: Date,
    default: Date.now
  },
  updatedAt: {
    type: Date,
    default: Date.now
  }
}, { strictQuery: false });

// Ensure both timeIn/checkIn and timeOut/checkOut are synced
AttendanceSchema.pre('save', function(next) {
  // Sync timeIn and checkIn (prefer checkIn if both are set)
  if (this.isModified('checkIn') || this.isModified('timeIn')) {
    const checkInValue = this.get('checkIn');
    const timeInValue = this.get('timeIn');
    const finalValue = checkInValue || timeInValue;
    this.set('checkIn', finalValue);
    this.set('timeIn', finalValue);
  }

  // Sync timeOut and checkOut (prefer checkOut if both are set)
  if (this.isModified('checkOut') || this.isModified('timeOut')) {
    const checkOutValue = this.get('checkOut');
    const timeOutValue = this.get('timeOut');
    const finalValue = checkOutValue || timeOutValue;
    this.set('checkOut', finalValue);
    this.set('timeOut', finalValue);
  }
  
  // For backwards compatibility - ensure teacherId is set if teacher is provided
  if (this.isModified('teacher') && this.teacher) {
    this.teacherId = this.teacher;
  }
  
  // Normalize the date by setting time to midnight
  if (this.isModified('date')) {
    const normalizedDate = new Date(this.date);
    normalizedDate.setHours(0, 0, 0, 0);
    this.date = normalizedDate;
  }

  next();
});

// Helper method to format the date as YYYY-MM-DD
AttendanceSchema.methods.getFormattedDate = function() {
  const date = this.date;
  return `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
};

// Custom error handling for duplicate key error
AttendanceSchema.post('save', function(error, doc, next) {
  if (error.name === 'MongoServerError' && error.code === 11000) {
    next(new Error('An attendance record already exists for this teacher on this date. Please update the existing record instead.'));
  } else {
    next(error);
  }
});

// Compound index to ensure one record per teacher per day
AttendanceSchema.index({ teacher: 1, date: 1 }, { unique: true });

const Attendance = mongoose.model('Attendance', AttendanceSchema);

module.exports = Attendance; 